 platform :ios, '13.0'

target 'Covid19_Internal_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Covid19_Internal
	pod 'Charts'
  pod ‘ReachabilitySwift’, ‘~> 3’

end
