source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '11.0'

target 'Covid19_Internal' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Covid19_Internal
	pod 'Charts'
end
