# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Covid19_Internal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid19_Internal
	pod 'Charts'
  pod ‘ReachabilitySwift’, ‘~> 3’
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'AWSS3'
  pod "VungleSDK-iOS", "6.8.0"
end
